### ISSUE TITLE
Data update problem

### ISSUE THREAD

**Issue by jarrodmcc** [quantumlib/OpenFermion-Psi4#14]
There appears to be a bug where a molecular data file will fail to update if a later calculation is done on the same molecule with an increased number of calculations.  For example, running:

```
from openfermion.hamiltonians import MolecularData
from openfermionpsi4 import run_psi4

geometry = [["H", [0, 0, 0]],
            ["H", [0, 0, 0.74]]]
basis = "sto-3g"
multiplicity = 1
charge = 0
h2_molecule = MolecularData(geometry, basis, multiplicity, charge)
h2_molecule = run_psi4(h2_molecule,
                       run_mp2=True,
                       run_cisd=True,
                       run_ccsd=True,
                       run_fci=True)

```
Will produce the correct result.  However, if one precedes the Psi4 computation by a less detailed calculation, i.e.

```
h2_molecule = run_psi4(h2_molecule)
h2_molecule = run_psi4(h2_molecule,
                       run_mp2=True,
                       run_cisd=True,
                       run_ccsd=True,
                       run_fci=True)
```

The data structure will fail to update with only some of the new data, specifically the energies.  That is, things like the RDMs will populate but the cisd_ and fci_energies will remain as None.  This appears to be an issued with the plugin rather than MolecularData generally, as this issue doesn't persist with the PySCF plugin.  Moreover, running PySCF plugin with updated data, WILL update the incomplete molecule as intended, but this plugin will not.

**Comment by babbush** [comment]
Jarrod is this still happening?

**Comment by jarrodmcc** [comment]
Unless someone has fixed it, I imagine that it does, as I still don't know the origin of the problem and why it's specific to Psi4.  I will test it again later

**Comment by babbush** [comment]
Closed by https://github.com/quantumlib/OpenFermion/pull/147
