### ISSUE TITLE
Better install instructions

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion-Psi4#2]
Psi4 needs to be configured with anaconda python. It would be great to have better instructions for this and possibly even provide a docker image. I'll take care of the better instructions when I have a chance.

**Comment by idk3** [comment]
Also, examples/plotter.py requires Tkinter (not currently installed with the plugin), and can't be run before examples/generate_data.py.

**Comment by babbush** [comment]
I do not consider Tkinter to be a requirement. For one thing, plotter.py isn't library code. For another, Tkinter comes with almost all standard python distributions. And it's not the only thing that would satisfy the requirement here. You need some graphics rendering abilities. Perhaps the problem is that you ssh tunneled into a system without X11 forwarding. For instance, perhaps if you tunnel using ssh - Y that would fix the problem?

**Comment by babbush** [comment]
Closed with https://github.com/quantumlib/OpenFermion-Psi4/pull/6
