### ISSUE TITLE
ImportError: cannot import name general_basis_change (_psi4_template)

### ISSUE THREAD

**Issue by conta877** [quantumlib/OpenFermion-Psi4#23]
fix: in [openfermionpsi4/_psi4_template](https://github.com/quantumlib/OpenFermion-Psi4/blob/abea45599ac3837879b7724983925bb2e35a7b41/openfermionpsi4/_psi4_template#L7) 

change from:

`from openfermion.ops import general_basis_change`

to 

`from openfermion.ops._polynomial_tensor import general_basis_change`

**Comment by babbush** [comment]
Thanks for this. In fact, the code works fine with the development version of OpenFermion but it throws an error with the latest PyPI version (the official OpenFermion v0.2). This raises the question of whether we should temporarily make the change you suggest or whether we should just push OpenFermion v0.3 to PyPI. The question is whether we have enough content for a new a release. @jarrodmcc @idk3 @kevinsung any thoughts?

**Comment by kevinsung** [comment]
It seems the problem is that OpenFermion is being changed without making sure that all its plugins remain compatible. In this case, perhaps we can make the change and update the version for just the plugin? After all, only code in the plugin needs to be changed.

**Comment by babbush** [comment]
Probably easier to just update the plugin - I'll do that later today then.

**Comment by kevinsung** [comment]
Oh, I just realized that in this case updating the OpenFermion version would also fix the bug, in a more "harmonious" way... But yeah it's easier to just fix the plugin.

**Comment by babbush** [comment]
Yep, that's what I was trying to say.
